---
title: "Eddy Covariance Checks"
author: "Alex Cebulski"
date: "28/02/2022"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.height=2, fig.width=8)
setwd("~/local-usask/analysis/eddy-cov/rmd")


library(data.table)
library(plotly)
library(tidyverse)
library(wxlogR)

# 3m EC data
ec15_low <- readRDS('../data/eddy_cov_15min_combined.rds') 

# ecHF1 <- wxlogR::load_CS_HF(path = '../../../field-downloads/fortress/hanging tree/hi freq/clean/TOA5_FRG_low_20220214.highfreq.dat')

ecHF1_low <- readRDS('../data/TOA5_FRG_low_20220214.highfreq.rds')

# 30 m EC data

ec30_high <- wxlogR::load_CS_1000(path = '../../../field-downloads/met-data/1000_ec/71489_EC_30min_2022-02-14T17-44.dat')

# met data from 1000x's on main tower
met <- wxlogR::load_CS_1000(path = '../../../field-downloads/met-data/1000_met/71490_MET_30min_2022-02-14T17-39.dat')
# met <- wxlogR::load_CS_1000(path = '../../../field-downloads/fortress/hanging tree/towercr1000/71490_MET_30min_2022-02-14T17-39.dat')

wnd_irtc <- wxlogR::load_CS_1000(path = '../../../field-downloads/met-data/1000x/6269_Fifteen_2022-02-14T17-35.dat')
```

## 15 Minute EC Data (3 m)

```{r, echo=FALSE}
ec15_low_long <- ec15_low %>% 
  pivot_longer(!TIMESTAMP)

ec30_high <- ec30_high %>% 
  pivot_longer(!TIMESTAMP)

met_long <- met %>% 
  select(TIMESTAMP, where(is.numeric)) %>% 
  pivot_longer(!TIMESTAMP)

wnd_irtc_long <- wnd_irtc %>% 
  pivot_longer(!TIMESTAMP)

df <- rbind(ec15_low_long, ec30_high, met_long, wnd_irtc_long)

col_names <- unique(df$name)

min_time_15 <- max(c(min(ec15_low$TIMESTAMP), min(met$TIMESTAMP)))
max_time_15 <- min(c(max(ec15_low$TIMESTAMP), max(met$TIMESTAMP)))

inputPanel(
  selectInput(inputId = 'var1', 
              label = '3 m EC Tower Variables: ', 
              choices = unique(ec15_low_long$name), 
              selected = c("result_wind_spd"), 
              multiple = T),
  selectInput(inputId = 'var2', 
              label = '30 m EC Tower Variables: ', 
              choices = unique(ec30_high$name), 
              selected = c("wnd_spd_Avg"), 
              multiple = T),
  selectInput(inputId = 'var3', 
              label = 'Met Tower Variables: ', 
              choices = c(unique(met_long$name), unique(wnd_irtc_long$name)), 
              selected = c("AirTC_Avg"), multiple = T),
  numericInput(
    inputId = 'fig_height',
    label = 'Figure Height in Pixels:',
    value = 150
  )
)


renderUI({
  sliderInput(inputId = "sliderTimeRange", label = "",
              min = min_time_15,
              max = max_time_15,
              value = c(min_time_15,
                        max_time_15),
              step = 3600,
              width = '100%',
              height )
})
```

```{r, echo=FALSE}
var1_df <-  reactive({
  req(input$var1)
  req(input$var2)
  req(input$var3)
  req(input$sliderTimeRange)
  
  df %>% 
    filter(name %in% c(input$var1, input$var2, input$var3),
          TIMESTAMP >= input$sliderTimeRange[1] & TIMESTAMP <= input$sliderTimeRange[2])
})

```


```{r, echo=FALSE}
output$var1_plot <- renderPlot(
      ggplot(data = var1_df(), aes(x = TIMESTAMP, y = value)) +
        geom_line() +
        facet_grid(rows = vars(name), scales = "free_y") +
        theme(
          axis.title.y = element_blank(),
          axis.title.x = element_blank()
        )
)

renderUI({
  plotOutput('var1_plot', height = length(c(input$var1, input$var2, input$var3))*input$fig_height)
})

```

# High Frequency EC Data (3 m)

```{r, echo=FALSE}

hf_names <- names(ecHF1_low)[!names(ecHF1_low) %in% c("TIMESTAMP", "RECORD")]
met_names <- names(met)[!names(met) %in% c("TIMESTAMP", "RECORD")]

min_time <- max(c(min(ecHF1_low$TIMESTAMP), min(met$TIMESTAMP)))
max_time <- min(c(max(ecHF1_low$TIMESTAMP), max(met$TIMESTAMP)))

inputPanel(
  selectInput(inputId = 'HFvar1', label = 'Variable 1: ', choices = hf_names),
)


    renderUI({
  sliderInput(inputId = "sliderTimeRangeHF", label = "",
              min = min_time,
              max = max_time,
              value = c(max_time - 3600*3,
                        max_time),
              step = 60,
              width = '100%',
              height )
})
```

```{r, echo=FALSE}
ecFilter <-  reactive({
  req(input$sliderTimeRangeHF)

  ecHF1_low %>% filter(TIMESTAMP>= input$sliderTimeRangeHF[1] & TIMESTAMP <= input$sliderTimeRangeHF[2])
})

```


```{r, echo=FALSE}
renderPlot(
      ggplot(data = ecFilter(), aes(x = TIMESTAMP)) +
        geom_line(aes_string(y = input$HFvar1)))
```