---
title: "Eddy Covariance Checks"
author: "Alex Cebulski"
date: "28/02/2022"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE, echo=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.height=2, fig.width=8)
setwd("~/local-usask/analysis/eddy-cov/rmd")

library(data.table)
library(plotly)
library(tidyverse)
library(wxlogR)
library(shiny)

# 3m EC data
getwd()

# ep_files <- c('../eddy-pro-cmd/data/output/eddypro_2016_calibrated_pars_full_output_2023-03-29T104926_exp.csv',
#               '../eddy-pro-cmd/data/output/eddypro_2016_calibrated_pars_full_output_2023-03-29T122318_exp.csv',
#               '../data/eddy_pro_output/eddypro_2016_calibrated_pars_full_output_2022-11-08T164432_exp.csv',
#               '../data/eddy_pro_output/eddypro_2016_calibrated_pars_full_output_2023-01-10T204008_exp.csv')

ep_files <- c('../eddy-pro-cmd/data/output/eddypro_2016_calibrated_pars_full_output_2023-09-01T120102_exp.csv',
              '../eddy-pro-cmd/data/output/eddypro_2016_calibrated_pars_full_output_2023-09-01T170105_exp.csv'
              )

ec_df_new <- purrr::map_dfr(ep_files, read.csv, skip = 1) |> 
  filter(!filename %in% c('not_enough_data', '')) |> 
  mutate(
    datetime = as.POSIXct(paste(date, time), tz = 'Etc/GMT+6'),
    across(DOY:w.h2o_cov, as.numeric)) |> 
  select(datetime,
         u_star = u.,
         Tau:qc_h2o_flux, 
         air_temperature, 
         air_pressure, 
         water_vapor_density,
         wind_speed,
         max_wind_speed, 
         wind_dir_mag = wind_dir, 
         used_records) |> 
  arrange(datetime)

ep_files <- c('../eddy-pro-cmd/data/output/eddypro_2016_calibrated_pars_full_output_2023-03-29T104926_exp.csv',
              '../eddy-pro-cmd/data/output/eddypro_2016_calibrated_pars_full_output_2023-03-29T122318_exp.csv',
              '../data/eddy_pro_output/eddypro_2016_calibrated_pars_full_output_2022-11-08T164432_exp.csv',
              '../data/eddy_pro_output/eddypro_2016_calibrated_pars_full_output_2023-01-10T204008_exp.csv')

ec_df_old <- purrr::map_dfr(ep_files, read.csv, skip = 1) |> 
  filter(!filename %in% c('not_enough_data', '')) |> 
  mutate(
    datetime = as.POSIXct(paste(date, time), tz = 'Etc/GMT+6'),
    across(DOY:w.h2o_cov, as.numeric)) |> 
  select(datetime,
         u_star = u.,
         Tau:qc_h2o_flux, 
         air_temperature, 
         air_pressure, 
         water_vapor_density,
         wind_speed,
         max_wind_speed, 
         wind_dir_mag = wind_dir, 
         used_records) |> 
  arrange(datetime)

# ec_df_logr <- readRDS('../../met-data-processing/data/ec_logr_15min_avg_low.rds') |> 
#   mutate(LE = -LE)

# raw

# ecHF1 <- wxlogR::load_CS_HF(path = '../../../field-downloads/fortress/hanging tree/hi freq/clean/TOA5_FRG_low_20220214.highfreq.dat')

# ecHF1_low <- readRDS('../data/TOA5_FRG_low_20220214.highfreq.rds')

# 15 m EC data

# ec_15m_logr <- readRDS('../../met-data-processing/data/waterloo_1000_ec_main.rds')

# met data from all loggers 
met <- readRDS('../../met-data-processing/data/ffr_t_rh_u_qaqc_fill.rds') 

```

## 15 Minute EC Data (3 m)

```{r, echo=FALSE, warning=FALSE}

ec_3m_old_long <- ec_df_old |> 
pivot_longer(!datetime)

ec_3m_new_long <- ec_df_new |> 
pivot_longer(!datetime)

# ec_3m_logr_long <- ec_df_logr |> 
# pivot_longer(!datetime)
# 
# ec_15m_logr_long <- ec_15m_logr |> 
# pivot_longer(!datetime)

met_long <- met |> 
pivot_longer(!datetime)

df <- rbind(ec_3m_old_long, ec_3m_new_long)

col_names <- unique(df$name)

min_time_15 <- max(c(min(ec_3m_old_long$datetime)))
max_time_15 <- min(c(max(ec_3m_old_long$datetime)))

inputPanel(
  selectInput(inputId = 'ec_3m_new_var', 
            label = '3 m EC New Processed Variables: ', 
            choices = unique(ec_3m_new_long$name), 
            selected = c("LE"), 
            multiple = F),
    selectInput(inputId = 'ec_3m_old_var', 
            label = '3 m EC Old Processed Variables: ', 
            choices = unique(ec_3m_old_long$name), 
            selected = c("LE"), 
            multiple = F),
# selectInput(inputId = 'ec_15m_logr_var', 
#             label = '15 m EC Logger Variables: ', 
#             choices = unique(ec_15m_logr_long$name), 
#             selected = c("LE_irga"), 
#             multiple = F),
# selectInput(inputId = 'met_var', 
#             label = 'Met Tower Variables: ', 
#             choices = unique(met_long$name), 
#             selected = c("air_temp"), multiple = T),
numericInput(
  inputId = 'fig_height',
  label = 'Figure Height in Pixels:',
  value = 250),
    numericInput(
  inputId = 'th_hi',
  label = 'Max Threshold:',
  value = 100),
    numericInput(
  inputId = 'th_low',
  label = 'Min Threshold:',
  value = -100
)
)


renderUI({
sliderInput(inputId = "sliderTimeRange", label = "",
            min = min_time_15,
            max = max_time_15,
            value = c(min_time_15,
                      max_time_15),
            step = 3600,
            width = '100%',
            height )
})
```

```{r, echo=FALSE}
ec_3m_new_long_fltr <-  reactive({
req(input$ec_3m_new_var)
req(input$sliderTimeRange)

ec_3m_new_long |> 
  filter(name %in% c(input$ec_3m_new_var),
        datetime >= input$sliderTimeRange[1] & datetime <= input$sliderTimeRange[2],
        value < input$th_hi,
        value > input$th_low) |> 
  mutate(group = paste0('3m_post_', input$ec_3m_new_var))
})

```

```{r, echo=FALSE}
ec_3m_old_long_fltr <-  reactive({
req(input$ec_3m_old_var)
req(input$sliderTimeRange)

ec_3m_old_long |> 
  filter(name %in% c(input$ec_3m_old_var),
        datetime >= input$sliderTimeRange[1] & datetime <= input$sliderTimeRange[2],
        value < input$th_hi,
        value > input$th_low) |> 
  mutate(group = paste0('3m_logr_', input$ec_3m_old_var))
})

```

```{r, echo=FALSE}
ec_bind <-  reactive({
req(input$sliderTimeRange)

rbind(ec_3m_old_long_fltr(), ec_3m_new_long_fltr())
})

```

```{r, echo=FALSE}
output$ec_bind_plot <- renderPlot(
    ggplot(data = ec_bind(), aes(x = datetime, y = value, colour = group)) +
      geom_line() +
      ylab("W m-2") +
      theme(
        axis.title.x = element_blank(),
        legend.position = 'bottom'
      )
)

renderUI({
plotOutput('ec_bind_plot', height = input$fig_height)
})

```

```{r, echo=FALSE}
met_long_fltr <-  reactive({
req(input$sliderTimeRange)
browser()
met_long |> 
  filter(name %in% c(input$met_var),
        datetime >= input$sliderTimeRange[1] & datetime <= input$sliderTimeRange[2],
        value < input$th_hi,
        value > input$th_low)
})

```

```{r, echo=FALSE}
output$met_plot <- renderPlot(
    ggplot(data = met_long_fltr(), aes(x = datetime, y = value)) +
      geom_line() +
      theme(
        axis.title.y = element_blank(),
        axis.title.x = element_blank()
      ) +
  facet_grid(rows = vars(name), 
             scales = 'free',
               switch = "y", # flip the facet labels along the y axis from the right side to the left
               # labeller = as_labeller( # redefine the text that shows up for the facets
               #   c(cur_good_vars))
             ) +
  ylab(NULL) + # remove the word "values"
  xlab(NULL) +
  theme(strip.background = element_blank(), # remove the background
        strip.placement = "outside")
)

renderUI({
plotOutput('met_plot', height = input$fig_height)
})

```
